export const serviceList = [
  "google",
  "facebook",
  "twitter",
  "instagram",
  "linkedin",
  "github",
  "discord",
  "meroshare",
  "tms",
  "connectips",
  "mobilebanking",
  "esewa",
  "imepay",
  "sip",
]

export const ownerList = [
  "sushil jaishi",
  "chintamani jaishi",
  "harikala jaishi",
  "parwati jaishi",
  "kritika jaishi",
  "himani jaisi",
  "aardhya jaisi",
  "aarad jaisi",
  "aakriti jaisi",
  "anisha thapa magar",
  "kunti devi thapa magar",
]
